### PR TITLE
new sysadmin error message

### PR DESCRIPTION
**Pull request by ninsaccplayzyt**
i am unsure if this will work at all as i dont have a bot to use to test it, nor a system to test it with, so @virtual-designer hopefully you can tell me if it will or not and if i need to make any changes

### CODE REVIEW

**Comment by virtual-designer** [comment]
This will work, but the problem is, this might confuse the users of the bot. I think for the main repo (this repo), we should not make this change.

**Comment by ninsaccplayzyt** [comment]
> but the problem is, this might confuse the users of the bot.

alrighty, if i end up making a pr on this again i would probably make it obvious at why it isnt working

**Comment by virtual-designer** [comment]
> > but the problem is, this might confuse the users of the bot.
> 
> alrighty, if i end up making a pr on this again i would probably make it obvious at why it isnt working
> 
> edit: probably shouldve defined what i meant by that, it would probs have like errors saying "you arent a system admin" and "you cannot run this because you are not a system admin", stuff like that

But you've changed the error messages... if you throw a `PermissionDeniedError` with a specific message the bot will show your custom error message.

**Comment by ninsaccplayzyt** [comment]
> But you've changed the error messages...

Oops, blame my sleepy coding 😭 pr can be closed if you wanna close it

**Comment by virtual-designer** [comment]
> > But you've changed the error messages...
> 
> Oops, blame my sleepy coding 😭 pr can be closed if you wanna close it

LMAO, it's all good. Closing now.

**Pull request closed without merging**
